# -*- mode: python ; coding: utf-8 -*-

block_cipher = None


a = Analysis(['nescience_rebalance.py'],
             pathex=['C:\\Users\\Julian\\AppData\\Local\\Programs\\Python\\Python36\\Nescience_Rebalance'],
             binaries=[],
             datas=[('C:\\Users\\Julian\\AppData\\Local\\Programs\\Python\\Python36\\Lib\\_strptime.py', '.'),
('C:\\Users\\Julian\\AppData\\Local\\Programs\\Python\\Python36\\Nescience_Rebalance\\Alpaca_refactored.py', '.'),
('C:\\Users\\Julian\\AppData\\Local\\Programs\\Python\\Python36\\Nescience_Rebalance\\BinancePeriodic.py', '.'),
('C:\\Users\\Julian\\AppData\\Local\\Programs\\Python\\Python36\\Nescience_Rebalance\\BitfinexPeriodic.py', '.'),
('C:\\Users\\Julian\\AppData\\Local\\Programs\\Python\\Python36\\Nescience_Rebalance\\BittrexPeriodic.py', '.'),
('C:\\Users\\Julian\\AppData\\Local\\Programs\\Python\\Python36\\Nescience_Rebalance\\GeminiPeriodic.py', '.'),
('C:\\Users\\Julian\\AppData\\Local\\Programs\\Python\\Python36\\Nescience_Rebalance\\HuobiPeriodic.py', '.'),
('C:\\Users\\Julian\\AppData\\Local\\Programs\\Python\\Python36\\Nescience_Rebalance\\KrakenPeriodic.py', '.'),
('C:\\Users\\Julian\\AppData\\Local\\Programs\\Python\\Python36\\Nescience_Rebalance\\KucoinPeriodic.py', '.'),
('C:\\Users\\Julian\\AppData\\Local\\Programs\\Python\\Python36\\Nescience_Rebalance\\LiquidPeriodic.py', '.'),
('C:\\Users\\Julian\\AppData\\Local\\Programs\\Python\\Python36\\Nescience_Rebalance\\OkExPeriodic.py', '.'),
('C:\\Users\\Julian\\AppData\\Local\\Programs\\Python\\Python36\\Nescience_Rebalance\\PoloniexPeriodic.py', '.'),
('C:\\Users\\Julian\\AppData\\Local\\Programs\\Python\\Python36\\Nescience_Rebalance\\UpbitPeriodic.py', '.'),
('C:\\Users\\Julian\\AppData\\Local\\Programs\\Python\\Python36\\Nescience_Rebalance\\GDAXPeriodic.py', '.')],
             hiddenimports=[],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          [],
          exclude_binaries=True,
          name='nescience_rebalance',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          console=True,icon='C:\\Users\\Julian\\Documents\\Whitepaper\\icon.ico')
coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               strip=False,
               upx=True,
               upx_exclude=[],
               name='Nescience_Rebalance')
